name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run:  npm install
    - name: Deploy to GH Pages
      env:
          CI: false
      run:
          git config --global user.email "aris.gani@gmail.com"
          git config --global user.name "Aris Abdulgani"
          npm run deploy

